version: 0.2
env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: brain-tasks-app
    IMAGE_TAG: latest
    CLUSTER_NAME: brain-tasks-cluster
    ACCOUNT_ID: 554903865969

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password>
      - echo Updating kubeconfig for EKS...
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - echo Tagging image for ECR...
      - docker tag $ECR_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:>

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo Updating Kubernetes deployment image...
      - kubectl set image deployment/brain-tasks-deployment brain-tasks=$ACCOUNT_ID.dkr.ecr.$AWS>
